#!/bin/bash
#
#

if cp BARK.cpp ethernet.cpp ethernet.hpp spi.cpp spi.hpp USART.hpp USART.cpp output/; then

    cd output
    if avr-gcc -g -Os -mmcu=atmega$1 -c BARK.cpp ethernet.cpp spi.cpp USART.cpp; then 
	avr-gcc -g -mmcu=atmega$1 -o flash.elf BARK.o ethernet.o spi.o USART.o
	avr-objcopy -j .text -j .data -O ihex flash.elf flash.hex
	#/// copy old data from avr to a old file, just in case its something importand
	#	sudo avrdude -c stk500v2 -p ATmega$1 -P /dev/ttyUSB$2 -U flash:r:.OLDmystery.hex:r
	#	uitgezet, want duurt te lang
	#
	#// program
	if [[ "$3" == "a" ]] ; then
	    echo 'Programming through arduino usb, bleg ugly'
	    sudo avrdude -c stk500v1 -p ATmega$1 -P /dev/tty$2 -U flash:w:flash.hex -F;
	elif [[ "$3" == "arduino" ]] ;  then
	    echo 'programming through arduino usb, bleg ugly'
	    sudo avrdude -c stk500v1 -p ATmega$1 -P /dev/tty$2 -U flash:w:flash.hex -F;
	elif [[ "$3" == "s" ]] ; then
	    echo 'programming with a real programmer (mySmartUsbLight)'
	    sudo avrdude -c stk500v2 -p ATmega$1 -P /dev/tty$2 -U flash:w:flash.hex;
	elif [[ "$3" == "smart" ]] ; then
	    echo 'programming with a real programmer (mySmartUsbLight)'
            sudo avrdude -c stk500v2 -p ATmega$1 -P /dev/tty$2 -U flash:w:flash.hex;
	else
	    echo 'ik niet snappo?'
	fi
    else
	echo "U faalt in programmeren, Lutser!";
    fi
else
    echo "er ging iets mis met copieren"
fi
